# Generated by Django 5.0.6 on 2024-06-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='is_activo',
            new_name='is_active',
        ),
    ]
