# Generated by Django 5.0.6 on 2024-06-15 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_is_activo_usuarios_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='date_joined',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='phone_number',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ultimo_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
